server:
  type: default
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 7777
  adminConnectors:
    - type: http
      port: 7778
swagger:
  description: Dropwizard Swagger
logging:
  level: INFO
